import 'package:flutter/material.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedToday1Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedCancelarWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/Generated\$5000Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedRectangle7Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedJuanBarriosPerfilWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/Generated26042023Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedVectorWidget19.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedAccount1Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/Generated\$20000Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/Generated\$15000Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedCorteMasculinoLimpiezaFacialWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedEllipse6Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedperfilwidget/generated/GeneratedServiciosofrecidosWidget.dart';

/* Frame perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 77, 198, 250),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 835.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 122.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07246376811594203;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.028459821428571428;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.5;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07729468599033816,
                        translateY: constraints.maxHeight * 0.9497767857142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget19())
                  ]);
                }),
              ),
              Positioned(
                left: 317.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedAccount1Widget1(),
              ),
              Positioned(
                left: 169.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedEllipse6Widget1(),
              ),
              Positioned(
                left: 189.0,
                top: 809.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedToday1Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 273.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 175.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 25.0,
                child: GeneratedCancelarWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 43.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 242.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 43.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 25.0,
                child: Generated26042023Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 25.0,
                child: Generated$20000Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 22.0,
                child: GeneratedTotalWidget(),
              ),
              Positioned(
                left: 287.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 25.0,
                child: Generated$15000Widget(),
              ),
              Positioned(
                left: 287.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 25.0,
                child: Generated$5000Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 56.0,
                child: GeneratedCorteMasculinoLimpiezaFacialWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 22.0,
                child: GeneratedServiciosofrecidosWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 285.0,
                height: 41.0,
                child: GeneratedJuanBarriosPerfilWidget(),
              )
            ]),
      ),
    ));
  }
}
