import 'package:flutter/material.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedHomeWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedEllipse5Widget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedToday1Widget2.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedImg11Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedEllipse5Widget3.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedVectorWidget26.dart';
import 'package:flutterapp/parcialwebapp/generatedhomewidget/generated/GeneratedAccount1Widget2.dart';

/* Frame home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 77, 198, 250),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 834.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 122.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 317.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedAccount1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07246376811594203;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.028459821428571428;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.5;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07729468599033816,
                        translateY: constraints.maxHeight * 0.9497767857142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget26())
                  ]);
                }),
              ),
              Positioned(
                left: 93.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 119.0,
                child: GeneratedEllipse5Widget3(),
              ),
              Positioned(
                left: 143.0,
                top: 54.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 46.0,
                child: GeneratedHomeWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 256.0,
                child: GeneratedImg11Widget1(),
              ),
              Positioned(
                left: 169.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedEllipse5Widget4(),
              ),
              Positioned(
                left: 189.0,
                top: 809.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedToday1Widget2(),
              ),
              Positioned(
                left: 42.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 177.0,
                child: GeneratedGroup7Widget(),
              )
            ]),
      ),
    ));
  }
}
