import 'package:flutter/material.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendamientowidget/generated/GeneratedAgendarcitasWidget2.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendamientowidget/generated/GeneratedEllipse5Widget2.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendamientowidget/generated/GeneratedFrame2Widget.dart';

/* Frame Agendamiento
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAgendamientoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 77, 198, 250),
                ),
              ),
              Positioned(
                left: 93.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 119.0,
                child: GeneratedEllipse5Widget2(),
              ),
              Positioned(
                left: 126.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 43.0,
                child: GeneratedAgendarcitasWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 747.0,
                child: GeneratedFrame2Widget(),
              )
            ]),
      ),
    ));
  }
}
