import 'package:flutter/material.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedVectorWidget2.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedEllipse5Widget1.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedAgendarcitasWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedToday1Widget.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedImg11Widget.dart';
import 'package:flutterapp/parcialmoviljuanapp/generatedagendarcitaswidget/generated/GeneratedAccount1Widget.dart';

/* Frame agendar citas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAgendarcitasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 77, 198, 250),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 834.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 122.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 317.0,
                top: 847.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedAccount1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07246376811594203;
                  double scaleX = (constraints.maxWidth * percentWidth) / 30.0;

                  double percentHeight = 0.028459821428571428;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 25.5;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07729468599033816,
                        translateY: constraints.maxHeight * 0.9497767857142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget2())
                  ]);
                }),
              ),
              Positioned(
                left: 93.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 119.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 354.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 43.0,
                child: GeneratedAgendarcitasWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 256.0,
                child: GeneratedImg11Widget(),
              ),
              Positioned(
                left: 169.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedEllipse5Widget1(),
              ),
              Positioned(
                left: 169.0,
                top: 790.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 75.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 189.0,
                top: 809.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedToday1Widget(),
              )
            ]),
      ),
    ));
  }
}
