import 'package:flutter/material.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedEmailWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedEmail2Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedNombreWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedBarberiaJuanBWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/Generated9740452Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedCorreoWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedLock1Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedEmail1Widget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedNombreWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedCorreogmailcomWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedregisterwidget/generated/GeneratedRectangle3Widget.dart';

/* Frame Register
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegisterWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 77, 198, 250),
                ),
              ),
              Positioned(
                left: 83.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 43.0,
                child: GeneratedBarberiaJuanBWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 153.0,
                child: Generated9740452Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 26.0,
                child: GeneratedCorreoWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 25.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 25.0,
                child: GeneratedEmailWidget1(),
              ),
              Positioned(
                left: 57.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 116.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 25.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 689.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedLock1Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 25.0,
                child: GeneratedCorreogmailcomWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 452.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 22.0,
                child: GeneratedNombreWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEmail1Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEmail2Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 25.0,
                child: GeneratedNombreWidget1(),
              )
            ]),
      ),
    ));
  }
}
