import 'package:flutter/material.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedBarberiaJuanBWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedLock1Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedCorreogmailcomWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedDeseasregistratePresioneaquWidget.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedEmail1Widget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/GeneratedCorreoWidget1.dart';
import 'package:flutterapp/parcialwebapp/generatedloginwidget/generated/Generated9740452Widget1.dart';

/* Frame log in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 77, 198, 250),
                ),
              ),
              Positioned(
                left: 92.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 26.0,
                child: GeneratedCorreoWidget1(),
              ),
              Positioned(
                left: 94.0,
                top: 428.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 25.0,
                child: GeneratedEmailWidget2(),
              ),
              Positioned(
                left: 59.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 57.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 116.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 25.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 75.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedLock1Widget1(),
              ),
              Positioned(
                left: 115.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 25.0,
                child: GeneratedCorreogmailcomWidget1(),
              ),
              Positioned(
                left: 75.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedEmail1Widget1(),
              ),
              Positioned(
                left: 57.0,
                top: 742.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 168.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 18.0,
                child: GeneratedDeseasregistratePresioneaquWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 43.0,
                child: GeneratedBarberiaJuanBWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 153.0,
                child: Generated9740452Widget1(),
              )
            ]),
      ),
    ));
  }
}
